Document: seasocks
Title: Debian seasocks Manual
Author: <insert document author here>
Abstract: This manual describes what seasocks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seasocks/seasocks.sgml.gz

Format: postscript
Files: /usr/share/doc/seasocks/seasocks.ps.gz

Format: text
Files: /usr/share/doc/seasocks/seasocks.text.gz

Format: HTML
Index: /usr/share/doc/seasocks/html/index.html
Files: /usr/share/doc/seasocks/html/*.html
