#!/bin/bash

set -e

pushd /tmp
GCC_HOME=$(fig -m gcc/5.2.0-1 -g GCC_HOME)
popd
export CC=${GCC_HOME}/bin/gcc
export CXX=${GCC_HOME}/bin/g++
GCC_MULTIARCH=$(gcc -print-multiarch 2>/dev/null)
if [[ "$GCC_MULTIARCH" != "" ]]; then
    export LIBRARY_PATH=/usr/lib/$GCC_MULTIARCH
    export C_INCLUDE_PATH=/usr/include/$GCC_MULTIARCH
    export CPLUS_INCLUDE_PATH=/usr/include/$GCC_MULTIARCH
fi
export LDFLAGS="-Wl,--rpath,${GCC_HOME}/lib64"
mkdir -p build
cd build
cmake ..
